/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router when `bun dev` is first run.
// Do not edit manually.

export const routeTree = {} as any;
